spring:
     r2dbc:
          url: r2dbc:postgresql://localhost:5432/sigei_users
          username: postgres
          password: postgres

     flyway:
          url: jdbc:postgresql://localhost:5432/sigei_users
          user: postgres
          password: postgres

     rabbitmq:
          host: localhost
          port: 5672
          username: guest
          password: guest

logging:
     pattern:
          console: "%d{HH:mm:ss.SSS} %highlight(%-5level) [%cyan(%logger{20})] %msg%n"
     level:
          pe.edu.vallegrande.sigei: DEBUG
          org.springframework.r2dbc: INFO
          io.r2dbc.postgresql: INFO
